### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder

### ISSUE THREAD

**Issue by jparkie** [jparkie/Aizoban#17]
````
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:620)
at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:825)
at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:817)
at android.support.v7.internal.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:554)
at android.support.v7.internal.app.ToolbarActionBar.setListMenuPresenter(ToolbarActionBar.java:558)
at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:178)
at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92)
at com.jparkie.aizoban.views.activities.MainActivity.initializeToolbar(MainActivity.java:144)
at com.jparkie.aizoban.presenters.MainPresenterImpl.initializeViews(MainPresenterImpl.java:55)
at com.jparkie.aizoban.views.activities.MainActivity.onCreate(MainActivity.java:47)
at android.app.Activity.performCreate(Activity.java:5122)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
at android.app.ActivityThread.access$600(ActivityThread.java:165)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5391)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
````

Affects mostly Samsung devices on Android 4.2.2: https://code.google.com/p/android/issues/detail?id=78377

**Comment by jparkie** [comment]
Closed for now until a more permanent fix. Currently, I cannot test the Proguard configuration as I do not have the devices which lead to the issue. I will rely on the users' crash reports.

**Comment by MisterY** [comment]
Did this workaround work for you?
